name: Python Multiple Versions

on:
    push:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                python-version: ["3.11","3.12","3.13"]

        steps:

            - name: checkout code
              uses: actions/checkout@v4

            - name: Set up python
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Run linter
              run: ruff check .

            - name: Run tests
              run: pytest

    
    build:

        needs: test
        runs-on: ubuntu-latest

        steps:

            - name: checkout code
              uses: actions/checkout@v4

            - name: Build application
              run: |
                zip -r my-python-app.zip app.py

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: my-python-app
                path: my-python-app.zip




# name: Python Multiple Versions

# on:
#     push:
#         branches: [main]

# jobs:
#     test:
#         runs-on: ubuntu-latest

#         strategy:
#             matrix:
#                 python-version: ["3.11","3.12","3.13"]

#         steps:

#             - name: checkout code
#               uses: actions/checkout@v4

#             - name: Set up python
#               uses: actions/setup-python@v5
#               with:
#                 python-version: ${{ matrix.python-version }}

#             - name: Install dependencies
#               run: pip install -r requirements.txt

#             - name: Run linter
#               run: ruff check .

#             - name: Run tests
#               run: pytest

#             - name: Build application
#               run: |
#                 zip -r my-python-app.zip app.py

#             - name: Upload artifact
#               uses: actions/upload-artifact@v4
#               with:
#                 name: my-python-app
#                 path: my-python-app.zip
